apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signal
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: signal
spec:
  project: signal
  source:
    repoURL: git@github.com:Wcamaly/signal.git
    targetRevision: main
    path: deploy/kustomize/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: signal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false